# Generated by Django 4.2.2 on 2023-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('pH', models.IntegerField()),
                ('dissolved_oxygen', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('conductivity', models.IntegerField()),
                ('turbidity', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('chlorine', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
            ],
        ),
    ]
